[theme]
primaryColor        = "#F5A623"
backgroundColor     = "#ffffff"
secondaryBackgroundColor = "#f5f6fa"
textColor           = "#1E2D6B"
font                = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true
